name: assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner:

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: NotoSans-Medium
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
    - family: NotoSans-Bold
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: NotoSans-ExtraBold
      fonts:
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
    - family: NotoSans-ExtraLight
      fonts:
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
    - family: NotoSans-Light
      fonts:
        - asset: assets/fonts/NotoSans-Light.ttf
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSans-SemiBold
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
    - family: NotoSans-Thin
      fonts:
        - asset: assets/fonts/NotoSans-Thin.ttf
    - family: NotoSans-Black
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf

#FontWeight.w100: 'Thin',
#  FontWeight.w200: 'ExtraLight',
#  FontWeight.w300: 'Light',
#  FontWeight.w400: 'Regular',
#  FontWeight.w500: 'Medium',
#  FontWeight.w600: 'SemiBold',
#  FontWeight.w700: 'Bold',
#  FontWeight.w800: 'ExtraBold',
#  FontWeight.w900: 'Black',